# 準備

## Googleドライブのマウント

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## sys.pathの設定

以下では，Googleドライブのマイドライブ直下にDNN_codeフォルダを置くことを仮定しています．必要に応じて，パスを変更してください．

In [2]:
import sys
sys.path.append('/content/drive/My Drive/Study-AI/step3')

# importと関数定義

In [3]:
import numpy as np
from common import functions

def print_vec(text, vec):
    print("*** " + text + " ***")
    print(vec)
    print("shape: " + str(vec.shape))
    print("")


# 順伝播（単層・単ユニット）

In [4]:
# 順伝播（単層・単ユニット）

# 重み
W = np.array([[0.1], [0.2]])

## 試してみよう_配列の初期化
#W = np.zeros(2)
#W = np.ones(2)
#W = np.random.rand(2)
#W = np.random.randint(5, size=(2))

print_vec("重み", W)


# バイアス
b = np.array(0.5)

## 試してみよう_数値の初期化
#b = np.random.rand() # 0~1のランダム数値
#b = np.random.rand() * 10 -5  # -5~5のランダム数値

print_vec("バイアス", b)

# 入力値
x = np.array([2, 3])
print_vec("入力", x)


# 総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.relu(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.1]
 [0.2]]
shape: (2, 1)

*** バイアス ***
0.5
shape: ()

*** 入力 ***
[2 3]
shape: (2,)

*** 総入力 ***
[1.3]
shape: (1,)

*** 中間層出力 ***
[1.3]
shape: (1,)



# 順伝播（単層・複数ユニット）

In [5]:
# 順伝播（単層・複数ユニット）

# 重み
W = np.array([
    [0.1, 0.2, 0.3,0], 
    [0.2, 0.3, 0.4, 0.5], 
    [0.3, 0.4, 0.5, 1],
])

## 試してみよう_配列の初期化
#W = np.zeros((4,3))
#W = np.ones((4,3))
#W = np.random.rand(4,3)
#W = np.random.randint(5, size=(4,3))

print_vec("重み", W)

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)

#  総入力
u = np.dot(W, x) + b
print_vec("総入力", u)

# 中間層出力
z = functions.sigmoid(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.1 0.2 0.3 0. ]
 [0.2 0.3 0.4 0.5]
 [0.3 0.4 0.5 1. ]]
shape: (3, 4)

*** バイアス ***
[0.1 0.2 0.3]
shape: (3,)

*** 入力 ***
[ 1.  5.  2. -1.]
shape: (4,)

*** 総入力 ***
[1.8 2.2 2.6]
shape: (3,)

*** 中間層出力 ***
[0.85814894 0.90024951 0.93086158]
shape: (3,)



# 順伝播（3層・複数ユニット）

In [6]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    input_layer_size = 3
    hidden_layer_size_1=10
    hidden_layer_size_2=5
    output_layer_size = 4
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size_1)
    network['W2'] = np.random.rand(hidden_layer_size_1,hidden_layer_size_2)
    network['W3'] = np.random.rand(hidden_layer_size_2,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size_1)
    network['b2'] =  np.random.rand(hidden_layer_size_2)
    network['b3'] =  np.random.rand(output_layer_size)

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("中間層出力2", z2)
    print_vec("総入力2", u2)
    print_vec("出力", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1, z2

# 入力値
x = np.array([1., 2., 4.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

*** 入力 ***
[1. 2. 4.]
shape: (3,)

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.88994665 0.87416772 0.83813938 0.95138742 0.09774978 0.57915592
  0.6089154  0.84245048 0.64546171 0.91680566]
 [0.3062251  0.00857692 0.47850081 0.71856277 0.21152233 0.51201889
  0.13270725 0.2654925  0.96951184 0.01180464]
 [0.88850202 0.06573398 0.34277843 0.04191323 0.32305241 0.18972733
  0.32709767 0.7021848  0.12536639 0.9610356 ]]
shape: (3, 10)

*** 重み2 ***
[[0.05244067 0.04541226 0.44742032 0.15444563 0.3170245 ]
 [0.28167096 0.44588144 0.39496458 0.8422576  0.46478179]
 [0.56424392 0.24577048 0.45595178 0.08416188 0.01373423]
 [0.03607283 0.06334391 0.96153527 0.55790223 0.37270312]
 [0.37369363 0.80927055 0.20410164 0.92298897 0.95877303]
 [0.71413429 0.5722436  0.64126489 0.11720809 0.19410359]
 [0.23551352 0.31572046 0.79159192 0.39517572 0.07256052]
 [0.14031488 0.8818184  0.63895836 0.88033169 0.56451439]
 [0.83847777 0.75400088 0.817501   0.04757235 0.98107269]
 [0.67523741 0.98152268 0.24211153

In [7]:
np.random.rand(3, 3)

array([[0.65585933, 0.20210314, 0.4909969 ],
       [0.07514563, 0.08143806, 0.12390474],
       [0.21929344, 0.34536978, 0.9212296 ]])

# 多クラス分類（2-3-4ネットワーク）

In [14]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-6 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}
    
    input_layer_size =  3
    hidden_layer_size=  10
    output_layer_size = 6
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2.,  3.])

# 目標出力
d = np.array([0, 0, 0, 1, 0, 0])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[0.90397409 0.65897513 0.83409815 0.51795367 0.8709845  0.34918267
  0.70613558 0.04270047 0.39780304 0.3421559 ]
 [0.702648   0.3353791  0.11648319 0.41142708 0.31289156 0.11150814
  0.6617622  0.72599492 0.92252268 0.36265556]
 [0.84408767 0.82666407 0.86512651 0.31784658 0.28229303 0.57389763
  0.19236604 0.7551803  0.77587779 0.86385376]]
shape: (3, 10)

*** 重み2 ***
[[0.22587734 0.74637983 0.97669387 0.86489266 0.19337484 0.82355412]
 [0.54166844 0.27409056 0.77783093 0.98847155 0.23477743 0.9859521 ]
 [0.73618069 0.84594159 0.45710031 0.12277969 0.56787695 0.15175889]
 [0.9511523  0.50793507 0.81460642 0.68434313 0.17256235 0.50192252]
 [0.2999923  0.29571301 0.20901763 0.09882653 0.69176382 0.99683112]
 [0.15045082 0.26841828 0.39127923 0.02941461 0.78665513 0.61413332]
 [0.95858734 0.46261619 0.4658016  0.06541216 0.83636888 0.96682262]
 [0.49710403 0.57243398 0.01346709 0.8675066  0.63690506 0.72551944]
 [0.28511433 0.27096548 0.12950748 0.37

## 考察
- 3-5-6では交差エントロピー誤差1.859、3-10-6では交差エントロピー誤差3.841
- 中間層が多ければ誤差が小さくなるわけではない

# 回帰（2-3-2ネットワーク）

In [19]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    input_layer_size =  3
    hidden_layer_size=  2
    output_layer_size = 2
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
    
    return y, z1

# 入力値
x = np.array([1., 2., 3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4.])
# 誤差
loss = functions.mean_squared_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("二乗誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[0.14740501 0.77525848]
 [0.48921609 0.29017034]
 [0.00519781 0.27260309]]
shape: (3, 2)

*** 重み2 ***
[[0.89527709 0.31995546]
 [0.99453378 0.28679275]]
shape: (2, 2)

*** バイアス1 ***
[0.48535658 0.46389111]
shape: (2,)

*** バイアス2 ***
[0.40943451 0.1195709 ]
shape: (2,)

##### 順伝播開始 #####
*** 総入力1 ***
[1.6267872  2.63729956]
shape: (2,)

*** 中間層出力1 ***
[1.6267872  2.63729956]
shape: (2,)

*** 総入力2 ***
[4.48874333 1.39642873]
shape: (2,)

*** 出力1 ***
[4.48874333 1.39642873]
shape: (2,)

出力合計: 5.885172061200424

##### 結果表示 #####
*** 中間層出力 ***
[1.6267872  2.63729956]
shape: (2,)

*** 出力 ***
[4.48874333 1.39642873]
shape: (2,)

*** 訓練データ ***
[2. 4.]
shape: (2,)

*** 二乗誤差 ***
3.243106675367426
shape: ()



## 考察
- 3-5-2では二乗誤差20.492、3-10-6では二乗誤差163.306
- このモデルでは中間層が少なければ単純に二乗誤差も小さくなるが適切なノード数が必要

# 2値分類（2-3-1ネットワーク）

In [20]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-20-1 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.array([
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1]
    ])
    network['W2'] = np.random.rand(10, 20)
    network['W3'] = np.random.rand(20, 1)

    network['b1'] = np.random.rand(10)
    network['b2'] =np.random.rand(20)
    network['b3'] =np.random.rand(1)

    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2, W3 = network['W1'], network['W2'],network['W3']
    b1, b2, b3 = network['b1'], network['b2'],network['b3']

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層1の総出力
    z1 = functions.relu(u1)
    # 隠れ層２層への総入力
    u2 = np.dot(z1, W2) + b2
    # 隠れ層2の出力
    z2 = functions.relu(u2)
    
    u3 = np.dot(z2, W3) + b3
    z3 = functions.sigmoid(u3)
    y = z3    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1

# 入力値
x = np.array([1., 2.,2.,4.,5.])

# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[2.24749266 4.97038926 7.98332748 2.30849677 5.14334321 7.66403378
 2.15017175 4.81607692 7.46218607 2.33190017]
shape: (10,)

*** 中間層出力1 ***
[2.24749266 4.97038926 7.98332748 2.30849677 5.14334321 7.66403378
 2.15017175 4.81607692 7.46218607 2.33190017]
shape: (10,)

*** 総入力2 ***
[28.7520376  27.86368609 15.66772377 11.89151912 26.35567064 21.45741281
 17.76865182 18.14618334 22.79532384 25.39981104 24.51344689 22.41119587
 20.59579956 27.08079963 18.71468293 18.86266956 22.99404565 26.63289615
 18.68438352 17.7299857 ]
shape: (20,)

*** 出力1 ***
[1.]
shape: (1,)

出力合計: 1.0

##### 結果表示 #####
*** 中間層出力 ***
[2.24749266 4.97038926 7.98332748 2.30849677 5.14334321 7.66403378
 2.15017175 4.81607692 7.46218607 2.33190017]
shape: (10,)

*** 出力 ***
[1.]
shape: (1,)

*** 訓練データ ***
[1]
shape: (1,)

*** 交差エントロピー誤差 ***
-9.999999505838704e-08
shape: ()

